
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'COUNT SYMBOLexpression : SYMBOL COUNT expressionexpression : SYMBOL expressionexpression : '
    
_lr_action_items = {'SYMBOL':([0,2,3,],[2,2,2,]),'$end':([0,1,2,3,4,5,],[-3,0,-3,-3,-2,-1,]),'COUNT':([2,],[3,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'expression':([0,2,3,],[1,4,5,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> expression","S'",1,None,None,None),
  ('expression -> SYMBOL COUNT expression','expression',3,'p_expression_count','test.py',39),
  ('expression -> SYMBOL expression','expression',2,'p_expression_symbol','test.py',45),
  ('expression -> <empty>','expression',0,'p_expression_symbCount','test.py',51),
]
