os: linux
dist: xenial
language: python
python:
- '3.6'
- '3.7'
- '3.8'
install:
- pip install -r requirements.txt
- pip install tox-travis
- pip install coverage
- pip install codecov
script:
- tox
- coverage run -m unittest discover
after_success:
- codecov
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  username: __token__
  password:
    secure: F1GqDGTFL3r53U7wcErUU9aGwv55DI7HoB001pzHqcW3p9EsxKvWMC7KMX8Y8RMAjunSpcklfjm9lA3hQZ0t8EWnz2dsENSKEKOG4hkJ+1TDctQL95dpxIq3JMEAO4/9Sjtw/hbkj4VWYQFWrUGM5oIRfl1P7eNZib6/KNLq8f6/PF3MRQiwXS1453n7SybsPV0Ym62wC68loTVqJh6M1G0s7QnhfpngurH6uBiMmCC5kibWWgwkVkEDccdyT/noUBxZ5BNTDjH+z+DfQwd+u30+2j+FbQgRNPANOK8TYINYHVYvHZ4UciQmx/SDxeMSRWoLdep9+jS6APj9oSHpjqDPLPFbgOQrnHqXW8+o7cByY6KvhxQcL509hQMcx8zbY9UiW1i0QTsFAuH/YW4XBqvS9yGD/UL7Jhpm6S8+wf2fGQhkIIYAd9dNJaoG9gKkmXyB5m2VxQ0MMhrBXg8qAmVuKQjA+jiYz/c3Eu+zmtWhv+QdJ8QZ2wEJEyuhw6rikCN/wPI6gcREn2kFhesE7ZhTZbz8Ww6UyCbhgl/IBSAt6OBImA88JFhqb0jrnljFbtFTjVul1oVW6SFPBWIVJFwzYPOe63XykBvaEZ0iR42Ib5+J3IUGJWFwrZj9ouX2kTap6AsUvLlqpDOL/ZWFlkjylQ5FlkMUrSXuvPvN84Q=
  on:
    tags: true
    repo: Vipul97/slr-parser
    python: 3.8
